version: 0.2

env:
  variables:
    IMAGE_NAME: ajaykumar91/brain-tasks-app
    IMAGE_TAG: latest
    AWS_REGION: us-east-1
    CLUSTER_NAME: brain-cluster

phases:

  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y curl unzip

      - echo "Installing AWS CLI..."
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install --update

      - echo "Installing kubectl..."
      - curl -o kubectl https://amazon-eks.s3.us-east-1.amazonaws.com/1.29.0/2024-01-04/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - echo "Logging into DockerHub..."
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - echo "Checking AWS identity..."
      - aws sts get-caller-identity

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $IMAGE_NAME:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push $IMAGE_NAME:$IMAGE_TAG

      - echo "Configuring kubeconfig for EKS..."
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - echo "Verifying cluster connection..."
      - kubectl get nodes

      - echo "Deploying to Kubernetes..."
      - kubectl apply -f kubernetes/deployment.yaml
      - kubectl apply -f kubernetes/service.yaml

      - echo "Deployment completed successfully!"
