env:
  variables:
    IMAGE_NAME: ajaykumar91/brain-tasks-app
    IMAGE_TAG: latest

phases:

  install:
    commands:
      - echo Installing dependencies...
      - apt-get update -y
      - apt-get install -y docker.io
      - docker --version

  pre_build:
    commands:
      - echo Logging into Docker Hub...
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

  build:
    commands:
      - echo Build started...
      - docker build -t $IMAGE_NAME:$IMAGE_TAG .

  post_build:
    commands:
      - echo Pushing image...
      - docker tag $IMAGE_NAME $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG
      - docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG

      # OPTIONAL: Deploy to Kubernetes
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region us-east-1 --name brain-eks-cluster

      - echo Deploying to EKS...
      - kubectl apply -f kubernetes/deployment.yaml
      - kubectl apply -f kubernetes/service.yaml

artifacts:
  files:
    - '**/*'