apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-app
  template:
    metadata:
      labels:
        app: brain-app
    spec:
      containers:
      - name: brain-app
        image: ajaykumar1998/brain-tasks-app:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"